-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 21, 2025 at 06:43 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `qgen`
--

-- --------------------------------------------------------

--
-- Table structure for table `contact_messages`
--

CREATE TABLE `contact_messages` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `message` text NOT NULL,
  `submitted_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `contact_messages`
--

INSERT INTO `contact_messages` (`id`, `name`, `email`, `message`, `submitted_at`) VALUES
(1, 'prajyot chandrapatle', 'praniitac01@gmail.com', 'dsdsdsdsd', '2025-07-29 04:44:30'),
(2, 'prajyot chandrapatle', 'praniitac01@gmail.com', 'gffffffffffff', '2025-08-04 06:24:41'),
(3, 'prajyot chandrapatle', 'praniitac01@gmail.com', 'jghjghjh', '2025-08-17 04:24:45'),
(4, 'prajyot chandrapatle', 'praniitac01@gmail.com', 'fghfghftghfgjhfg', '2025-08-17 04:44:00'),
(5, 'Prajyot Siddharam Chandrapatale gfhfghfg', 'praniitac01@gmail.comhgfhgfhgfhgf', 'fghfghfghfhfhfhfghfgh', '2025-08-17 04:44:14'),
(6, 'prajyot chandrapatle', 'praniitac01@gmail.com', 'nvcnbcncn', '2025-08-19 14:03:59');

-- --------------------------------------------------------

--
-- Table structure for table `qgen_history`
--

CREATE TABLE `qgen_history` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `generator` enum('basic','advanced') NOT NULL,
  `task_name` varchar(150) DEFAULT NULL,
  `table_name` varchar(255) NOT NULL,
  `columns_text` text DEFAULT NULL,
  `query_line` text DEFAULT NULL,
  `full_query` longtext NOT NULL,
  `generated_functions` longtext NOT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `qgen_history`
--

INSERT INTO `qgen_history` (`id`, `user_id`, `generator`, `task_name`, `table_name`, `columns_text`, `query_line`, `full_query`, `generated_functions`, `created_at`) VALUES
(1, 21, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', '', '2025-08-14 09:58:44'),
(4, 35, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 10:40:36'),
(5, 35, 'basic', NULL, 'employee', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `employee` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `employee`;\n\n-- UPDATE QUERY --\nUPDATE `employee` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `employee` WHERE `age` = ?;', 'function insert_employee_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `employee` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_employee_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `employee`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_employee_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `employee` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_employee_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `employee` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 10:40:41'),
(6, 35, 'basic', NULL, 'qgen_registration', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 10:40:46'),
(7, 35, 'advanced', 'get_paginated', 'qgen_registration', 'id,email_id,PASSWORD', 'SELECT * FROM qgen_registration LIMIT ? OFFSET ?;', 'function get_qgen_registration_data_paginated($limit, $offset)\r\n{\r\n    $query = \"SELECT * FROM qgen_registration LIMIT ? OFFSET ?\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"ii\", $limit, $offset);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function get_qgen_registration_data_paginated($limit, $offset)\r\n{\r\n    $query = \"SELECT * FROM qgen_registration LIMIT ? OFFSET ?\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"ii\", $limit, $offset);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-14 10:42:03'),
(8, 21, 'basic', NULL, 'student', 'age,salary,address,blood group,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `salary`, `address`, `blood group` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_salary, $var_address, $var_blood group)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?)\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_salary, $var_address, $var_blood group);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `salary`, `address`, `blood group` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_salary, $res_address, $res_blood group);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'salary\'] = $res_salary;\n        $data[$row_no][\'address\'] = $res_address;\n        $data[$row_no][\'blood group\'] = $res_blood group;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_salary, $var_address, $var_blood group, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"sssss\", $var_age, $var_salary, $var_address, $var_blood group, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 19:17:42'),
(9, 21, 'basic', NULL, 'student', 'age,salary,address,blood group,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `salary`, `address`, `blood group` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_salary, $var_address, $var_blood group)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?)\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_salary, $var_address, $var_blood group);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `salary`, `address`, `blood group` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_salary, $res_address, $res_blood group);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'salary\'] = $res_salary;\n        $data[$row_no][\'address\'] = $res_address;\n        $data[$row_no][\'blood group\'] = $res_blood group;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_salary, $var_address, $var_blood group, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"sssss\", $var_age, $var_salary, $var_address, $var_blood group, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 19:18:56'),
(10, 21, 'advanced', 'update_by_id', 'qgen_registration', 'age,name,no,', 'UPDATE qgen_registration SET age = ?, name = ?, no = ? WHERE age = ?;', 'function update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE qgen_registration SET age = ?, name = ?, no = ? WHERE age = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', 'function update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE qgen_registration SET age = ?, name = ?, no = ? WHERE age = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 19:19:58'),
(11, 21, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 19:45:57'),
(12, 21, 'basic', NULL, 'qgen_registration', 'age,salary,address,blood group,', NULL, '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `salary`, `address`, `blood group` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_salary, $var_address, $var_blood group)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?)\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_salary, $var_address, $var_blood group);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `salary`, `address`, `blood group` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_salary, $res_address, $res_blood group);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'salary\'] = $res_salary;\n        $data[$row_no][\'address\'] = $res_address;\n        $data[$row_no][\'blood group\'] = $res_blood group;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_salary, $var_address, $var_blood group, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"sssss\", $var_age, $var_salary, $var_address, $var_blood group, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-14 19:55:23'),
(13, 21, 'basic', NULL, 'qgen_registration', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:46:47'),
(14, 21, 'basic', NULL, 'employee', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `employee` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `employee`;\n\n-- UPDATE QUERY --\nUPDATE `employee` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `employee` WHERE `age` = ?;', 'function insert_employee_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `employee` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_employee_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `employee`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_employee_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `employee` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_employee_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `employee` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:50:34'),
(15, 21, 'advanced', 'get_paginated', 'qgen_registration', 'age,name,no', 'SELECT * FROM qgen_registration LIMIT ? OFFSET ?;', 'function get_qgen_registration_data_paginated($limit, $offset)\r\n{\r\n    $query = \"SELECT * FROM qgen_registration LIMIT ? OFFSET ?\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"ii\", $limit, $offset);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function get_qgen_registration_data_paginated($limit, $offset)\r\n{\r\n    $query = \"SELECT * FROM qgen_registration LIMIT ? OFFSET ?\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"ii\", $limit, $offset);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:50:55'),
(16, 21, 'basic', NULL, 'qgen_registration', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:51:37'),
(17, 21, 'basic', NULL, 'klkl', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `klkl` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `klkl`;\n\n-- UPDATE QUERY --\nUPDATE `klkl` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `klkl` WHERE `age` = ?;', 'function insert_klkl_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `klkl` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_klkl_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `klkl`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_klkl_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `klkl` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_klkl_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `klkl` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:55:36'),
(18, 36, 'basic', NULL, 'qgen_registration', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:57:14'),
(19, 36, 'advanced', 'get_by_column', 'qgen_registration', 'age,name,no,', 'SELECT * FROM qgen_registration WHERE $column = ?;', 'function get_qgen_registration_by_column($column, $value)\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT * FROM qgen_registration WHERE $column = ?\")) {\r\n        $stmt->bind_param(\"s\", $value);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function get_qgen_registration_by_column($column, $value)\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT * FROM qgen_registration WHERE $column = ?\")) {\r\n        $stmt->bind_param(\"s\", $value);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-15 13:57:27'),
(20, 36, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 14:02:26'),
(21, 36, 'basic', NULL, 'gdfgdf', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `gdfgdf` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `gdfgdf`;\n\n-- UPDATE QUERY --\nUPDATE `gdfgdf` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `gdfgdf` WHERE `age` = ?;', 'function insert_gdfgdf_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `gdfgdf` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_gdfgdf_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `gdfgdf`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_gdfgdf_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `gdfgdf` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_gdfgdf_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `gdfgdf` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 14:06:51'),
(22, 36, 'basic', NULL, 'siri', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `siri` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `siri`;\n\n-- UPDATE QUERY --\nUPDATE `siri` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `siri` WHERE `age` = ?;', 'function insert_siri_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `siri` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_siri_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `siri`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_siri_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `siri` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_siri_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `siri` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 14:07:04'),
(23, 36, 'basic', NULL, 'employee', 'id', NULL, '-- INSERT QUERY --\nINSERT INTO `employee` (`id`) VALUES (?);\n\n-- SELECT QUERY --\nSELECT `id` FROM `employee`;\n\n-- UPDATE QUERY --\nUPDATE `employee` SET `id` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `employee` WHERE `id` = ?;', 'function insert_employee_data($var_id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `employee` (`id`) VALUES (?)\")) {\r\n        $stmt->bind_param(\"s\", $var_id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_employee_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id` FROM `employee`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_employee_by_id($var_id, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `employee` SET `id` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ss\", $var_id, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_employee_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `employee` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 14:07:19'),
(24, 36, 'basic', NULL, 'qgen_registration', 'age,salary,address,blood group,', NULL, '', 'function insert_qgen_registration_data($var_age, $var_salary, $var_address, $var_blood group)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?)\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_salary, $var_address, $var_blood group);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `salary`, `address`, `blood group` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_salary, $res_address, $res_blood group);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'salary\'] = $res_salary;\n        $data[$row_no][\'address\'] = $res_address;\n        $data[$row_no][\'blood group\'] = $res_blood group;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_salary, $var_address, $var_blood group, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"sssss\", $var_age, $var_salary, $var_address, $var_blood group, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 14:13:46'),
(25, 36, 'basic', NULL, 'employee', 'age,name,no,', NULL, '', '', '2025-08-15 14:14:17'),
(26, 36, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-15 14:14:38'),
(27, 21, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 09:00:12'),
(28, 21, 'basic', NULL, 'student', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 13:07:25'),
(29, 21, 'basic', NULL, 'employee', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `employee` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `employee`;\n\n-- UPDATE QUERY --\nUPDATE `employee` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `employee` WHERE `age` = ?;', 'function insert_employee_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `employee` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_employee_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `employee`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_employee_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `employee` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_employee_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `employee` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 13:07:46'),
(30, 21, 'basic', NULL, 'student', 'age,salary,address,blood group,', 'SELECT age, salary, address, blood group,  FROM student;', 'SELECT age, salary, address, blood group,  FROM student;', 'function getData() { ... }', '2025-08-17 13:13:11'),
(31, 21, 'basic', NULL, 'siri', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `siri` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `siri`;\n\n-- UPDATE QUERY --\nUPDATE `siri` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `siri` WHERE `age` = ?;', 'function insert_siri_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `siri` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_siri_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `siri`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_siri_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `siri` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_siri_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `siri` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 13:20:50'),
(32, 21, 'basic', NULL, 'siri', 'age,name,no,', NULL, '-- INSERT QUERY --\nINSERT INTO `siri` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `siri`;\n\n-- UPDATE QUERY --\nUPDATE `siri` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `siri` WHERE `age` = ?;', 'function insert_siri_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `siri` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_siri_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `siri`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_siri_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `siri` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_siri_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `siri` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 13:21:27'),
(33, 21, 'basic', NULL, 'klkl', 'age,name,no,', '', '-- INSERT QUERY --\nINSERT INTO `klkl` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `klkl`;\n\n-- UPDATE QUERY --\nUPDATE `klkl` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `klkl` WHERE `age` = ?;', 'function insert_klkl_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `klkl` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_klkl_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `klkl`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_klkl_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `klkl` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_klkl_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `klkl` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 13:28:20');
INSERT INTO `qgen_history` (`id`, `user_id`, `generator`, `task_name`, `table_name`, `columns_text`, `query_line`, `full_query`, `generated_functions`, `created_at`) VALUES
(34, 21, 'basic', NULL, 'qgen_registration', 'age,name,no,', '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-17 13:31:37'),
(35, 21, 'advanced', 'count_all', 'employee', 'id,email_id,PASSWORD', 'SELECT COUNT(*) as total FROM employee;', 'function count_employee_records()\r\n{\r\n    $result = $this->con->query(\"SELECT COUNT(*) as total FROM employee\");\r\n    return $result->fetch_assoc()[\'total\'] ?? 0;\r\n}', 'function count_employee_records()\r\n{\r\n    $result = $this->con->query(\"SELECT COUNT(*) as total FROM employee\");\r\n    return $result->fetch_assoc()[\'total\'] ?? 0;\r\n}', '2025-08-17 13:39:53'),
(36, 21, 'advanced', 'get_history', 'student', 'age,name,no,', '-- Unknown or unsupported task.', '⚠️ Task not implemented or invalid.', '⚠️ Task not implemented or invalid.', '2025-08-18 19:37:49'),
(37, 21, 'basic', NULL, 'qgen_registration', 'age,name,no,', '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-18 19:57:17'),
(38, 21, 'basic', NULL, 'student', 'age,salary,address,blood group,', '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `salary`, `address`, `blood group` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `salary`, `address`, `blood group` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `age` = ?;', 'function insert_student_data($var_age, $var_salary, $var_address, $var_blood group)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`age`, `salary`, `address`, `blood group`) VALUES (?, ?, ?, ?)\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_salary, $var_address, $var_blood group);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `salary`, `address`, `blood group` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_salary, $res_address, $res_blood group);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'salary\'] = $res_salary;\n        $data[$row_no][\'address\'] = $res_address;\n        $data[$row_no][\'blood group\'] = $res_blood group;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_age, $var_salary, $var_address, $var_blood group, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `age` = ?, `salary` = ?, `address` = ?, `blood group` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"sssss\", $var_age, $var_salary, $var_address, $var_blood group, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 10:36:59'),
(39, 21, 'basic', NULL, 'qgen_registration', 'age,name,no,', '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', '-- INSERT QUERY --\nINSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `age`, `name`, `no` FROM `qgen_registration`;\n\n-- UPDATE QUERY --\nUPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `qgen_registration` WHERE `age` = ?;', 'function insert_qgen_registration_data($var_age, $var_name, $var_no)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `qgen_registration` (`age`, `name`, `no`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_age, $var_name, $var_no);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_qgen_registration_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `age`, `name`, `no` FROM `qgen_registration`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_age, $res_name, $res_no);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'age\'] = $res_age;\n        $data[$row_no][\'name\'] = $res_name;\n        $data[$row_no][\'no\'] = $res_no;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_qgen_registration_by_id($var_age, $var_name, $var_no, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `qgen_registration` SET `age` = ?, `name` = ?, `no` = ? WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_age, $var_name, $var_no, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_qgen_registration_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `qgen_registration` WHERE `age` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 11:12:34'),
(40, 21, 'advanced', 'get_paginated', 'employee', 'age,name,no,', 'SELECT * FROM employee LIMIT ? OFFSET ?;', 'function get_employee_data_paginated($limit, $offset)\r\n{\r\n    $query = \"SELECT * FROM employee LIMIT ? OFFSET ?\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"ii\", $limit, $offset);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function get_employee_data_paginated($limit, $offset)\r\n{\r\n    $query = \"SELECT * FROM employee LIMIT ? OFFSET ?\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"ii\", $limit, $offset);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:10:34'),
(41, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:13:08'),
(42, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:28:13'),
(43, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:30:41'),
(44, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:30:59'),
(45, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:33:41'),
(46, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:35:12'),
(47, 21, 'advanced', 'search_data', 'qgen_registration', 'id,email_id,PASSWORD', 'SELECT * FROM qgen_registration WHERE id LIKE CONCAT(\'%\', ?, \'%\') OR email_id LIKE CONCAT(\'%\', ?, \'%\') OR PASSWORD LIKE CONCAT(\'%\', ?, \'%\');', 'function search_qgen_registration_data($keyword)\r\n{\r\n    $query = \"SELECT * FROM qgen_registration WHERE id LIKE CONCAT(\'%\', ?, \'%\') OR email_id LIKE CONCAT(\'%\', ?, \'%\') OR PASSWORD LIKE CONCAT(\'%\', ?, \'%\')\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"sss\", $keyword, $keyword, $keyword);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function search_qgen_registration_data($keyword)\r\n{\r\n    $query = \"SELECT * FROM qgen_registration WHERE id LIKE CONCAT(\'%\', ?, \'%\') OR email_id LIKE CONCAT(\'%\', ?, \'%\') OR PASSWORD LIKE CONCAT(\'%\', ?, \'%\')\";\r\n    if ($stmt = $this->con->prepare($query)) {\r\n        $stmt->bind_param(\"sss\", $keyword, $keyword, $keyword);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-19 20:35:30'),
(48, 21, 'advanced', 'get_by_column', 'student', 'age,salary,address,blood group,', 'SELECT * FROM student WHERE $column = ?;', 'function get_student_by_column($column, $value)\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT * FROM student WHERE $column = ?\")) {\r\n        $stmt->bind_param(\"s\", $value);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function get_student_by_column($column, $value)\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT * FROM student WHERE $column = ?\")) {\r\n        $stmt->bind_param(\"s\", $value);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-20 13:44:17'),
(49, 21, 'advanced', 'get_by_column', 'student', 'age,salary,address,blood group,', 'SELECT * FROM student WHERE $column = ?;', 'function get_student_by_column($column, $value)\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT * FROM student WHERE $column = ?\")) {\r\n        $stmt->bind_param(\"s\", $value);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', 'function get_student_by_column($column, $value)\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT * FROM student WHERE $column = ?\")) {\r\n        $stmt->bind_param(\"s\", $value);\r\n        $stmt->execute();\r\n        return $stmt->get_result()->fetch_all(MYSQLI_ASSOC);\r\n    }\r\n    return false;\r\n}', '2025-08-20 13:44:20'),
(50, 21, 'basic', NULL, 'student', 'id,email_id,PASSWORD', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', '-- INSERT QUERY --\nINSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?);\n\n-- SELECT QUERY --\nSELECT `id`, `email_id`, `PASSWORD` FROM `student`;\n\n-- UPDATE QUERY --\nUPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?;\n\n-- DELETE QUERY --\nDELETE FROM `student` WHERE `id` = ?;', 'function insert_student_data($var_id, $var_email_id, $var_PASSWORD)\r\n{\r\n    if ($stmt = $this->con->prepare(\"INSERT INTO `student` (`id`, `email_id`, `PASSWORD`) VALUES (?, ?, ?)\")) {\r\n        $stmt->bind_param(\"sss\", $var_id, $var_email_id, $var_PASSWORD);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction get_student_data()\r\n{\r\n    if ($stmt = $this->con->prepare(\"SELECT `id`, `email_id`, `PASSWORD` FROM `student`\")) {\r\n        $stmt->execute();\r\n        $stmt->bind_result($res_id, $res_email_id, $res_PASSWORD);\r\n        $data = [];\r\n        $row_no = 0;\r\n        while ($stmt->fetch()) {\r\n        $data[$row_no][\'id\'] = $res_id;\n        $data[$row_no][\'email_id\'] = $res_email_id;\n        $data[$row_no][\'PASSWORD\'] = $res_PASSWORD;\n        $row_no++;\r\n        }\r\n        return $data;\r\n    }\r\n    return false;\r\n}\n\nfunction update_student_by_id($var_id, $var_email_id, $var_PASSWORD, \\$id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"UPDATE `student` SET `id` = ?, `email_id` = ?, `PASSWORD` = ? WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"ssss\", $var_id, $var_email_id, $var_PASSWORD, \\$id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}\n\nfunction delete_student_by_id($id)\r\n{\r\n    if ($stmt = $this->con->prepare(\"DELETE FROM `student` WHERE `id` = ?\")) {\r\n        $stmt->bind_param(\"s\", $id);\r\n        return $stmt->execute();\r\n    }\r\n    return false;\r\n}', '2025-08-20 13:54:49');

-- --------------------------------------------------------

--
-- Table structure for table `qgen_registration`
--

CREATE TABLE `qgen_registration` (
  `id` int(11) NOT NULL,
  `email_id` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `signup_date` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `qgen_registration`
--

INSERT INTO `qgen_registration` (`id`, `email_id`, `PASSWORD`, `signup_date`) VALUES
(1, 'praniitac01@gmail.com', '11111', '2025-07-24 19:12:44'),
(2, 'praa@gmail.com', '22222', '2025-07-24 19:12:44'),
(3, 'praniidddddddddtac01@gmail.com', '44444', '2025-07-24 19:12:44'),
(4, 'praniitac01@gmail.com', '11111', '2025-07-24 19:12:44'),
(19, 'praniitac00000000001@gmail.com', '111111', '2025-07-24 19:12:44'),
(20, 'praniitac0111@gmail.com', '111111', '2025-07-24 19:12:44'),
(21, 'pppraniitac01@gmail.com', '222222', '2025-07-25 09:22:40'),
(22, 'prannnnnnnnnnnnniitac01@gmail.com', '111111', '2025-07-25 09:32:52'),
(23, 'praniitfgfgfgfgfac01@gmail.com', '5555555', '2025-07-25 09:35:15'),
(24, 'phfghfhraniitac01@gmail.com', '999999', '2025-07-25 09:36:10'),
(25, 'praniitdgdgdfgdfgfdgac01@gmail.com', '111111', '2025-07-25 14:37:12'),
(26, 'pranhfghfghfghfghiitac01@gmail.com', '111111', '2025-07-26 09:39:24'),
(27, 'praftfthfhfthfniitac01@gmail.com', '111111', '2025-07-26 09:39:57'),
(28, 'prahhhfddfhfniitac01@gmail.com', '111111', '2025-07-26 10:08:19'),
(29, 'pranffffiitac01@gmail.com', '111111', '2025-07-26 10:08:38'),
(31, 'praniitac01@gmail.comghghgh', '222222', '2025-07-26 10:15:19'),
(32, 'praniggdfggfdgfgitac01@gmail.com', '555555', '2025-07-26 10:30:33'),
(33, 'prangffdgfdgiitac01@gmail.com', 'llllll', '2025-07-26 10:31:32'),
(34, 'pranffdgiitac01@gmail.com', '222222', '2025-07-27 12:45:20'),
(35, 'praniitac01@gmail.comdfggg', '666666', '2025-07-27 16:33:03'),
(36, 'pradsgdfgdfgniitac01@gmail.com', '111111', '2025-07-30 10:40:41');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `contact_messages`
--
ALTER TABLE `contact_messages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `qgen_history`
--
ALTER TABLE `qgen_history`
  ADD PRIMARY KEY (`id`),
  ADD KEY `idx_user` (`user_id`);

--
-- Indexes for table `qgen_registration`
--
ALTER TABLE `qgen_registration`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `contact_messages`
--
ALTER TABLE `contact_messages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `qgen_history`
--
ALTER TABLE `qgen_history`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

--
-- AUTO_INCREMENT for table `qgen_registration`
--
ALTER TABLE `qgen_registration`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=84;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `qgen_history`
--
ALTER TABLE `qgen_history`
  ADD CONSTRAINT `fk_history_user` FOREIGN KEY (`user_id`) REFERENCES `qgen_registration` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
